/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BBlockquote: typeof import('./src/components/common/b-blockquote/b-blockquote.vue')['default']
    BButton: typeof import('./src/components/common/b-button/b-button.vue')['default']
    BCheckbox: typeof import('./src/components/common/b-checkbox/b-checkbox.vue')['default']
    BDivider: typeof import('./src/components/common/b-divider/b-divider.vue')['default']
    BIcon: typeof import('./src/components/common/b-icon/b-icon.vue')['default']
    BImage: typeof import('./src/components/common/b-image/b-image.vue')['default']
    BInputPassword: typeof import('./src/components/common/b-input-password/b-input-password.vue')['default']
    BInputText: typeof import('./src/components/common/b-input-text/b-input-text.vue')['default']
    BLink: typeof import('./src/components/common/b-link/b-link.vue')['default']
    BTelnum: typeof import('./src/components/common/b-telnum/b-telnum.vue')['default']
    BTitle: typeof import('./src/components/common/b-title/b-title.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonNavigation: typeof import('./src/components/portal/portal-button-navigation/button-navigation.vue')['default']
    PortalAccordion: typeof import('./src/components/portal/portal-accordion/portal-accordion.vue')['default']
    PortalAccordionContent: typeof import('./src/components/portal/portal-accordion/portal-accordion-content.vue')['default']
    PortalAccordionHeader: typeof import('./src/components/portal/portal-accordion/portal-accordion-header.vue')['default']
    PortalAccordionPanel: typeof import('./src/components/portal/portal-accordion/portal-accordion-panel.vue')['default']
    PortalButtonNavigation: typeof import('./src/components/portal/portal-button-navigation/portal-button-navigation.vue')['default']
    PortalCard: typeof import('./src/components/portal/portal-card/portal-card.vue')['default']
    PortalContent: typeof import('./src/components/portal/portal-content/portal-content.vue')['default']
    PortalInformationMenu: typeof import('./src/components/portal/portal-information-menu/portal-information-menu.vue')['default']
    PortalPage: typeof import('./src/components/portal/portal-page/portal-page.vue')['default']
    PortalPanel: typeof import('./src/components/portal/portal-panel/portal-panel.vue')['default']
    PortalUserCard: typeof import('./src/components/portal/portal-user-card/portal-user-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
