/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('./src/components/common/b-button/b-button.vue')['default']
    BCheckbox: typeof import('./src/components/common/b-checkbox/b-checkbox.vue')['default']
    BIcon: typeof import('./src/components/common/b-icon/b-icon.vue')['default']
    BImage: typeof import('./src/components/common/b-image/b-image.vue')['default']
    BInputPassword: typeof import('./src/components/common/b-input-password/b-input-password.vue')['default']
    BInputText: typeof import('./src/components/common/b-input-text/b-input-text.vue')['default']
    BLink: typeof import('./src/components/common/b-link/b-link.vue')['default']
    BTitle: typeof import('./src/components/common/b-title/b-title.vue')['default']
    PortalCard: typeof import('./src/components/portal/portal-card/portal-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
