export const dashboardPaths = {
    Dashboard:                  "/dashboard",
    DashboardPanel:             "/dashboard/panel",
    DashboardTickets:           "/dashboard/tickets",
    DashboardTicket:            "/dashboard/tickets/:id",
    DashboardUsers:             "/dashboard/users",
    DashboardUser:              "/dashboard/users/:id",
    DashboardPartners:          "/dashboard/partners/list",
    DashboardPartner:           "/dashboard/partners/list/:id",
    DashboardPartnerGroups:     "/dashboard/partners/groups",
    DashboardPartnerGroup:      "/dashboard/partners/groups/:id",
    DashboardCloudList:         "/dashboard/cloud",
    DashboardCloud:             "/dashboard/cloud/:id",
    DashboardRoyalty:           "/dashboard/royalty",
    DashboardStatisticsStaff:   "/dashboard/statistics/staff",
    DashboardStatisticsPartner: "/dashboard/statistics/partner",
}
