export enum DashboardRouteName {
    DashboardPanel = "DashboardPanel",
    DashboardTickets = "DashboardTickets",
    DashboardTicket = "DashboardTicket",
    DashboardUsers = "DashboardUsers",
    DashboardUser = "DashboardUser",
    DashboardPartners = "DashboardPartners",
    DashboardPartner = "DashboardPartner",
    DashboardPartnerGroups = "DashboardPartnerGroups",
    DashboardPartnerGroup = "DashboardPartnerGroup",
    DashboardPartnerNotifications = "DashboardPartnerNotifications",
    DashboardPartnerNotification = "DashboardPartnerNotification",
    DashboardPartnerMessage = "DashboardPartnerMessage",
    DashboardCloud = "DashboardCloud",
    DashboardCloudList = "DashboardCloudList",
    DashboardRoyaltyPercent = "DashboardRoyaltyPercent",
    DashboardRoyaltyRecords = "DashboardRoyaltyRecords",
    DashboardStatisticsStaff = "DashboardStatisticsStaff",
    DashboardStatisticsPartner = "DashboardStatisticsPartner",
    DashboardEventCalendarList = "DashboardEventCalendarList",
    DashboardEventCalendar = "DashboardEventCalendar",
    DashboardSettings = "DashboardSettings",
    DashboardMaintenance = "DashboardMaintenance",
    DashboardPayrollPartner = "DashboardPayrollPartner",
    DashboardPayrollStaff = "DashboardPayrollStaff",
}
