export const portalPaths = {
    Home: "/home",
    DocumentSubscription: "/documents/subscription",
    DocumentCertificate: "/documents/certificate",
    DocumentFines: "/documents/fines",
    DocumentFinesAudit: "/documents/fines-audit",
    DocumentMangoAudit: "/documents/mango-audit",
    ServicePaidCO: "/services/paid-co",
    ServiceSubscription: "/services/subscription",
    ServiceUserAnalytics: "/services/user-analytics",
    ServiceMissedCalls: "/services/missed-calls",
    InstructionMangoRedirect: "/instruction/mango-redirect",
    InstructionYclientNotifications: "/instruction/yclient-notifications",
    AdditionallyDiscount: "/additionally/discount",
    ContactCentralOffice: "/contacts/central-office",
    ContactFranchisee: "/contacts/franchisee",
    ContactPartners: "/contacts/partners",
}
