export enum PortalRouteName {
    Home = "PortalHome",
    DocumentSubscription = "PortalDocumentSubscription",
    DocumentCertificate = "PortalDocumentCertificate",
    DocumentFines = "PortalDocumentFines",
    DocumentFinesAudit = "PortalDocumentFinesAudit",
    DocumentMangoAudit = "PortalDocumentMangoAudit",
    ServicePaidCO = "ServicePaidCO",
    ServiceSubscription = "ServiceSubscription",
    ServiceUserAnalytics = "ServiceUserAnalytics",
    ServiceMissedCalls = "ServiceMissedCalls",
    InstructionMangoRedirect = "InstructionMangoRedirect",
    InstructionYclientNotifications = "InstructionYclientNotifications",
    AdditionallyDiscount = "AdditionallyDiscount",
    ContactCentralOffice = "ContactCentralOffice",
    ContactFranchisee = "ContactFranchisee",
    ContactPartners = "ContactPartners",
}
