export const profilePaths = {
    Profile:                    "/profile",
    ProfileUserProfile:         "/profile/user-profile",
    ProfileChangePassword:      "/profile/change-password",
    ProfileStatisticsStaff:     "/profile/statistics/staff",
    ProfileTeam:                "/profile/team",
    ProfileTicket:              "/profile/ticket/:id",
    ProfileTickets:             "/profile/tickets",
    ProfileTicketGeneral:       "/profile/ticket/general",
    ProfileTicketDesign:        "/profile/ticket/design",
    ProfileTicketCertificate:   "/profile/ticket/certificate",
    ProfileTicketSpecialist:    "/profile/ticket/specialist",
    ProfileTicketBlacklist:     "/profile/ticket/blacklist",
    ProfileTicketFlagman:       "/profile/ticket/flagman",
    ProfileTicketAdministrator: "/profile/ticket/administrator",
    ProfileTicketOpening:       "/profile/ticket/opening",
}
